name: GitHub Readme Stats

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch: # Allows you to run it manually

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: anuraghazra/github-readme-stats@master
        with:
          # Your GitHub username
          username: racheetsaraswat
          # The secret you just created
          token: ${{ secrets.GH_TOKEN }}
      - name: Commit and push generated stats
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add generated-stats.svg
          git commit -m 'Update generated-stats.svg' || echo "No changes to commit"
          git push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
